BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "messaggi_ricevuti" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"idMitt"	INTEGER NOT NULL,
	"text"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "messaggi_inviati" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"idDest"	INTEGER NOT NULL,
	"text"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "Contatti" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"surname"	TEXT NOT NULL,
	PRIMARY KEY("id")
);
COMMIT;
